# Generated by Django 4.1.7 on 2023-04-18 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shazam', '0005_privatechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechat',
            name='Host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Host', to=settings.AUTH_USER_MODEL),
        ),
    ]
